Fixes bytes literals issue
The subprocess returns bytes, which need to be decoded. This fixes an issue I was encountering where the following error message was being returned:


```
ERROR: Error 3004 - Error in cluster configuration: Master IP not valid. Valid ones are: b'<REDACTED IP>
```